### ISSUE TITLE
Issue in TainFunctionRequest.cs

### ISSUE THREAD

**Issue by ghost** [JarkoDubbeldam/TrainController#13]
I encountered an Issue while trying to send a TrainFunctionRequest to the Z21.
Whenever i wan't to set either the "SmartSearch" or "DoubleTraction" TrainFunction, the ArgumentException on line 18 is raised.
This is caused by the absence of these 2 Enum-Values in the TrainFunctionOrder List.
How would i need to alter the TrainFunctionOrder List to be able to use these 2 Functions?
Kind regards

**Comment by JarkoDubbeldam** [comment]
From what I can tell, these are read-only flags. There's no way to set them through the z21 API. The DoubleTraction feature, where you run two trains in sync, is something you enable by programming the decoder. I'm guessing that if this is done, the DoubleTraction flag will be set when fetching the train functions through the API.

I'm not sure what SmartSearch exactly does.

**Comment by ghost** [comment]
Thanks for confirming my suspicion. I came to the same conclusion after reading the Z21 LAN Protocol Manual...
Therefore i think we can close this issue.
