### ISSUE TITLE
Can you explain how to get Occupancy messages from R-Bus

### ISSUE THREAD

**Issue by CaptnMo** [JarkoDubbeldam/TrainController#3]
I am trying to get the occupancy messages in order to create some logic but I do not understand how to access them.
Best regards

**Comment by JarkoDubbeldam** [comment]
Sorry for the late reply. 

If you have a UDP connection with the Z21 client there is a specific call you can use to explicitly fetch the statuses, or to subscribe to any changes. [Here](https://www.z21.eu/media/Kwc_Basic_DownloadTag_Component/root-en-main_47-1652-959-downloadTag-download/default/3acee30b/1611850676/z21-lan-protocol-v1-10-en.pdf) you can find the specs for the protocol. The relevant part is section 7.

If your question was about the hardware part, it depends a bit on what you use. I only really have experience with the Digikeijs detectors.
